<?php

namespace ISC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActiviteImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteImageRepository extends EntityRepository
{
}
