<?php

namespace ISC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use \DateTime;
use \DateTimeZone;

/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRepository extends EntityRepository
{

    /**
     * @param $idUser
     * @param $listIdFriend
     * @return array
     */
    public function getActivites($idUser, $listIdFriend)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->where('a.user = :idUser')
            ->setParameter('idUser', $idUser);
        $nbFriend = (count($listIdFriend));
        for ($i=0; $i < $nbFriend; $i++) {
            $qb
                ->orWhere('a.user = :friendId'.$listIdFriend[$i])
                ->setParameter('friendId'.$listIdFriend[$i], $listIdFriend[$i]);
        }
        $qb
            ->andWhere('a.approved = true')
            ->leftJoin('a.image', 'image')
            ->addSelect('image')
            ->orderBy('a.datetimeActivity', 'DESC')
            ->setMaxResults(5);
        return $qb
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $idUser
     * @param $listIdFriend
     * @return array
     */
    public function getNbActivite($idUser, $listIdFriend)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->where('a.user = :idUser')
            ->setParameter('idUser', $idUser);
        $nbFriend = (COUNT($listIdFriend));
        for ($i=0; $i < $nbFriend; $i++) {
            $qb
                ->orWhere('a.user = :friendId'.$listIdFriend[$i])
                ->setParameter('friendId'.$listIdFriend[$i], $listIdFriend[$i]);
        }
        $qb
            ->orderBy('a.datetimeActivity', 'DESC');
        return $qb
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $idActu
     * @return array
     */
    public function getActuForEdit($idActu)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->where('a.id = :idActu')
            ->setParameter('idActu', $idActu)
            ->andWhere('a.approved = false')
            ->leftJoin('a.image', 'image')
            ->addSelect('image');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    /**
     * @param $idUser
     * @param $listIdFriend
     * @param $lastIdActu
     * @return array
     */
    public function getActivitesAfterId($idUser, $listIdFriend, $lastIdActu)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->where('a.user = :idUser')
            ->setParameter('idUser', $idUser);
        $nbFriend = (count($listIdFriend));
        for ($i=0; $i < $nbFriend; $i++) {
            $qb
                ->orWhere('a.user = :friendId'.$listIdFriend[$i])
                ->setParameter('friendId'.$listIdFriend[$i], $listIdFriend[$i]);
        }
        $qb
            ->andWhere('a.id < :lastIdActu')
            ->setParameter('lastIdActu', $lastIdActu)
            ->andWhere('a.approved = true')
            ->leftJoin('a.image', 'image')
            ->addSelect('image')
            ->orderBy('a.datetimeActivity', 'DESC')
            ->setMaxResults(5);
        return $qb
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $idUser
     * @return array
     */
    public function getNbActivites($idUser)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->where('a.user = :idUser')
            ->setParameter('idUser', $idUser)
            ->orderBy('a.datetimeActivity', 'DESC');
        return $qb
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $idUser
     * @return array
     */
    public function getNbImage($idUser)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->where('a.user = :idUser')
            ->setParameter('idUser', $idUser)
            ->andWhere('a.approved = true')
            ->andWhere('a.image != :imageStt')
            ->setParameter('imageStt', NULL)
            ->leftJoin('a.image', 'image')
            ->addSelect('image')
            ->orderBy('a.datetimeActivity', 'DESC');
        return $qb
            ->getQuery()
            ->getResult();
    }
}
