<?php

namespace ISC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserNotifsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNotifsRepository extends EntityRepository
{
    public function getUserNotifications($idUser)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->where('a.userTo = :idUser')
            ->andWhere('a.userFrom != :idUser')
            ->setParameter('idUser', $idUser)
            ->orderBy("a.datetimeNotif", 'DESC')
            ->setMaxResults(5);

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getIfMultiUserNotif($idUser, $idActu)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->where('a.userTo = :idUser')
            ->andWhere('a.userFrom != :idUser')
            ->setParameter('idUser', $idUser)
            ->andWhere('a.activite = :idActu')
            ->setParameter('idActu', $idActu)
            ->orderBy("a.datetimeNotif", 'DESC');

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getNbMyNewNotif($idUser)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->where('a.userTo = :idUser')
            ->andWhere('a.userFrom != :idUser')
            ->andWhere('a.view = 0')
            ->setParameter('idUser', $idUser)
            ->setMaxResults(5);

        return $qb
            ->getQuery()
            ->getResult();
    }
}
