<?php

namespace ISC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserFriendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFriendRepository extends EntityRepository
{
    /**
     * @param $idUser
     * @return array
     */
    public function getFriendId($idUser)
    {
    	$qb = $this->createQueryBuilder('a');

		$qb
			->select('a.idFriend')
		    ->where('a.user = :idUser')
		    ->setParameter('idUser', $idUser)
		    ->andWhere('a.approvedFriend = 1')
		;
		$listFriendId = $qb->getQuery()->getResult();
		$arrayFriendId = [];
		$nbFriend = (COUNT($listFriendId));
		for ($i=0; $i < $nbFriend; $i++) {
			$arrayFriendId[$i] = $listFriendId[$i]['idFriend'];
		}
		return $arrayFriendId;
    }

    /**
     * @param $idUser
     * @return array
     */
    public function getNewInvit($idUser)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->select('a')
            ->where('a.idFriend = :idFriend')
            ->setParameter('idFriend', $idUser)
            ->andWhere('a.approvedFriend = 0');
        return $qb
            ->getQuery()
            ->getResult();
    }
}
