isc_platform_homepage:
    path:     /
    methods: [ get ]
    defaults: { _controller: ISCPlatformBundle:Accueil:index }

isc_platform_homepage_create_activite:
    path:     /
    methods: [ post ]
    defaults: { _controller: ISCPlatformBundle:Accueil:createActivite }

isc_platform_homepage_add_like_actu:
    path:     /add-like-actu/
    methods: [ get ]
    defaults: { _controller: ISCPlatformBundle:Accueil:addLike }

isc_platform_homepage_remove_like_actu:
    path:     /remove-like-actu/
    methods: [ get ]
    defaults: { _controller: ISCPlatformBundle:Accueil:removeLike }

isc_platform_get_notification:
    path:     /notifications
    methods: [ get ]
    defaults: { _controller: ISCPlatformBundle:Accueil:notif }

isc_platform_view_actu:
    path:     /visualisation-d-actualite/{idActu}
    methods: [ get ]
    defaults: { _controller: ISCPlatformBundle:Accueil:viewActu }

isc_platform_homepage_load_more_actu:
    path:     /load-more-actu
    methods: [ get ]
    defaults: { _controller: ISCPlatformBundle:Accueil:loadMore }

isc_platform_search:
    path:     /search
    methods: [ get ]
    defaults: { _controller: ISCPlatformBundle:Accueil:search }

isc_platform_homepage_pixie_actualite:
    path:     /edition-image-activite/{filename}/{idActu}
    methods: [ get ]
    defaults: { _controller: ISCPlatformBundle:Accueil:editImageActu }

isc_platform_homepage_pixie_actualite_save:
    path:     /profil/save-image-activite/
    methods: [ post ]
    defaults: { _controller: ISCPlatformBundle:Accueil:saveImageActivite }

isc_platform_view_image_public:
    path:     /visualisation-image/{username}/{idActu}
    methods: [ get ]
    defaults: { _controller: ISCPlatformBundle:Visiteurs:viewImagePublic }

isc_platform_profil_membres:
    path:     /profil/{username}
    methods: [ get ]
    options:
        expose: true
    defaults: { _controller: ISCPlatformBundle:Profil:index }

isc_platform_profil_membres_create_activite:
    path:     /profil/{username}
    methods: [ post ]
    defaults: { _controller: ISCPlatformBundle:Profil:createActivite }

isc_platform_homepage_send_invite_to_membre:
    path:     /send-invite-to-membre/
    methods: [ get ]
    defaults: { _controller: ISCPlatformBundle:Profil:sendInvitToMembre } #Anciennement sur le controller accueil

isc_platform_homepage_accept_invite_of_member:
    path:     /accept-invite-of-membre/
    methods: [ get ]
    defaults: { _controller: ISCPlatformBundle:Profil:acceptInvitOfMember }

isc_platform_homepage_refuse_invite_of_member:
    path:     /refuse-invite-of-membre/
    methods: [ get ]
    defaults: { _controller: ISCPlatformBundle:Profil:refuseInvitOfMember }

isc_platform_profil_show_image:
    path:     /profil/{username}/images
    defaults: { _controller: ISCPlatformBundle:Profil:showImage }

isc_platform_profil_pixie_avatar:
    path:     /profil/edition-avatar/{filename}
    defaults: { _controller: ISCPlatformBundle:Profil:editAvatar }
