# src/ISC/PlatformBundle/Resources/config/services.yml
#    isc_platform.example:
#        class: ISC\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    isc_platform.accueil:
        class:      ISC\PlatformBundle\Accueil\ISCAccueil
        arguments:  [@doctrine.orm.entity_manager, @service_container]