services:
    isc_platform.user:
        class:      ISC\PlatformBundle\User\ISCUser
        arguments:  [@doctrine.orm.entity_manager, @service_container]
    isc_platform.activite:
        class:      ISC\PlatformBundle\Activite\ISCActivite
        arguments:  [@doctrine.orm.entity_manager, @isc_platform.user, @service_container]
        tags:
            -  { name: twig.extension }