<?php

namespace ISC\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param $motcle
     * @return array
     */
    public function getSearchListUser($motcle)
	{
		$qb = $this->createQueryBuilder('a');
		$qb
		    ->where('a.username LIKE :username')
		    ->setParameter('username', '%'.$motcle.'%');
		return $qb
        	->getQuery()
		    ->getResult();
	}
}
